### ISSUE TITLE
Web app missing messages from some but not all senders in group message

### ISSUE THREAD

**Issue by hokfujow** [klinker-apps/pulse-sms-issues#1005]
I'm finding that in some group messages, the android app shows them all, but those from particular individuals are missing when viewed in the web app. In addition, it appears that when I send using the web app, some but not all of my messages are not making back out - again, in group messages. 

This only happens using web app.
My biggest reason for using pulse is the availability of a synchronized web app, so this is particularly problematic.

**Comment by klinker24** [comment]
If the messages that you send from the web show up on the phone, then the web app successfully delivered it to the phone to be sent (which is its job). #101 tracks issues related to sending MMS messages and provides information on what you can try if messages are not being sent or not being sent consistently. We will have all MMS sending related discussions there, rather than in individual issues. This issue has now been linked there.

If some messages aren't showing up on the web, I would just recommend refreshing your account from the phone app. This will re-upload your messages from the phone and reset any connections with the backend. Messages are just uploaded to the web when they come in through the phone app. If your phone doesn't have an internet connection, that could prevent them from uploading or they could be uploaded at a later time.
