### ISSUE TITLE
Changing primary device via the web app

### ISSUE THREAD

**Issue by meaghanc18** [klinker-apps/pulse-sms-issues#1022]
## Confirm this Issue

- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [x] This is not a general support questions. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

I would like to be able to change which device is the primary device remotely. While it is useful to be able to not have to look at every device I have I was also hoping to be able to access messages on any device that I have it installed on in case of screen damage which I am prone to. 

### Describe alternatives you've considered

I cannot think of another way than remotely changing the primary device via the browser, I understand the device would need to be powered on, connected to mobile network with the app already installed and signed in to My account.

### Additional information

This app has worked real well on a partially damaged phone to be able to continue sending and receiving from that number until I can replace the device but I already had it set up, I would like to do the same to any device I have as a non primary remotely in case it becomes unresponsive without having to purchase it for every device and sideload multiple instances of the app.

**Comment by klinker24** [comment]
I don't think that changing your primary device from the web app would solve the situation that you are proposing it would. Changing the primary device wouldn't suddenly let you view a different set of messages. That just isn't how Pulse is designed. Pulse will work with a single phone number and set of messages at a time. That isn't going to change, Pulse just doesn't support that and likely will never support that.

If you have Pulse on different phones with different phone numbers and want to be able to see each of their message sets, you would need to just separate Pulse accounts on each device and log in to the account you want to view. You don't have to pay for each device/account. As long as the device is logged in to the Google account you made the purchase with, you can create different pulse accounts.

The reason that I have never allowed for this is because it could totally ruin your Pulse account to change the primary device. I only allow for changing the primary device when you log in to the new device to ensure that the device is actually active and can be made primary.
