### ISSUE TITLE
Improve preventative/diagnostic troubleshooting for primary/secondary issues

### ISSUE THREAD

**Issue by jcrben** [klinker-apps/pulse-sms-issues#810]
NOTE: I don't think this is super high priority - and as I understand it better now, I doubt it will cause me more frustration. So feel free to close it. But working on smoothing out this experience could prevent some support down the line.

**Device with issue:** Google Pixel & LG V20
**Primary device:** Ex: Pixel XL on Android 9
**App version:** 4.3.4.2313

**Describe the bug:**
A couple weeks ago, I upgraded from an LG V20 to a Google Pixel 2. While I was getting used to the Google Pixel, I continued to primarily use the LG V20. I don't remember the exact details of my upgrade process, but I let Google import most of the apps. Possibly when I first opened Pulse on the Pixel, I did not make it the primary but I don't recall.

When I started using the Pixel as my main device in the past week, I turned off my LG V20. I started sending messages with Pulse. As it turns out, these weren't sent, but the Android Messages app worked.

I eventually uninstalled / reinstalled the app and set it as primary, which addressed the issue. Reading the "I have two phones..." help (https://messenger.klinkerapps.com/help/ - NOTE that anchor tags and being able to copy/paste these headers would be awesome), I see that the secondary device forwards to the primary which then sends the message. So it makes sense to me that the primary must be on.

**Expected behavior:**
Suggested improvements:
1. I expect that the primary device would send all the messages when I turn it on, even several days later. Possibly this is working properly and I somehow messed it up

2. This might be a feature request rather than a bug thing, but it would be best if it could detect that the message was never sent and warn accordingly? Not sure about whether that is technically possible. 

3. The situation is made confusing by the way that the app isn't really upfront about whether it's primary or secondary - I could tell indirectly thru the "My Account" settings missing the "Refresh" option (after reading the help page carefully). Some sort of in-app warning or banner about the secondary status notifying the user that the messages that you are sending require the primary device to be on could help avoid this confusing troubleshooting.

**Comment by klinker24** [comment]
To address all of these

1. It won't, no. Firebase cloud messaging only provides so many "pending" push notifications. Pulse uses push notifications to deliver all information between devices. If your device is turned off for an extended amount of time, it will not receive those notifications when it turns back on. Since it cannot receive the notifications, it cannot send the pending messages.
2. I don't think that this is something that will be possible. Technically, those messages are still "pending" whether they are sent or not. There is just a disconnect between FCM and the app that likely isn't something that can be overcome easily.
3. The web app now displays the primary device on the account. If you go to "my account" -> "devices", the first one that shows up is the primary. This is documented in other places, but it can be documented here, as well

I am going to close this one. At this time, there isn't anything actionable that I can do
