### ISSUE TITLE
Avatar icons doesn't update

### ISSUE THREAD

**Issue by Enn83** [klinker-apps/pulse-sms-issues#953]
**_Device with issue :_** Huawei Honor 9 STF-L09, **EMUI Versuin** 9.1.0, **Android Version** 9, **PULSE android version** the last update (5.1.0.2697).

When I update avatar (or set a new avatar to one which doesn't have avatar) in my phone, the avatar doesn't appears in the Pulse app, even if I clear cache or close the app.

**Comment by klinker24** [comment]
Clearing the cache would update the icon. Setting an icon to a contact that didn't have one should be fixed with this commit, whenever it gets released. However, you might have to reinstall the app for it to work.

https://github.com/klinker-apps/pulse-sms-android/commit/078f5210aeb83cc4f2bd086e3a4101a363e069e0
