### ISSUE TITLE
Update Schedule Message UX

### ISSUE THREAD

**Issue by sstream17** [klinker-apps/pulse-sms-issues#959]
## Confirm this Issue

- [x] This is something that I am looking to code myself and create a PR for, not a feature request for @klinker24 to code.
- [x] This is a larger change that I am considering, which I would like feedback on, to discuss implementation details, or to confirm whether or not this is something that would be merged into the app.

### Describe Your Request

I would like to update the workflow of scheduled messages to create a more consistent user experience throughout the app. The main idea is using the `ComposeActivity` to start the process from the `ScheduledMessagesFragment`.

<table>
<tr>
    <td>1. The process is started from the Scheduled Messages screen by pressing the FAB</td>
    <td>2. The ComposeActivity is launched allowing the user to pick contacts in a way that is familiar to them</td>
    <td>3. The app then opens to the MessageList and shows a single dialog where the user can pick the date, time, and repeat mode of the message. The date and time inputs will open the current DatePicker and TimePicker dialogs</td>
</tr>
<tr>
    <td>
        <img src="https://user-images.githubusercontent.com/38381547/73599110-98dd1480-4505-11ea-82b6-41e10e770124.png" alt="Step 1">
    </td>
    <td>
        <img src="https://user-images.githubusercontent.com/38381547/73599114-a2667c80-4505-11ea-97f0-ff443564142c.png" alt="Step 2">
    </td>
    <td>
        <img src="https://user-images.githubusercontent.com/38381547/73599117-ab574e00-4505-11ea-993c-74970e4dc0d3.png" alt="Step 3">
    </td>
</tr>
<tr>
    <td>4. The scheduled time then appears while the user enters the message. Hitting the send button will save the schedule message</td>
    <td>*5. The ScheduledMessageFragment is then displayed in the attachment holder to let the user know the message has been saved</td>
</tr>
<tr>
    <td>
        <img src="https://user-images.githubusercontent.com/38381547/73599124-b7dba680-4505-11ea-9167-8e05a321167c.png" alt="Step 4">
    </td>
    <td>
        <img src="https://user-images.githubusercontent.com/38381547/73599136-c1650e80-4505-11ea-9e97-71d84a410a58.png" alt="Step 5">
    </td>
</tr>
</table>

I am most of the way there for implementing this. It is probably a crude implementation so I'm hoping a PR code review can iron out most of the details.
*I am the least set on step 5. I am trying to think of better ways to signal to the user the message has been scheduled. If we would like to keep this way of doing it, I would need some help on implementing it. I am not sure the best way to access the `attachHolder`. Trying to get to get it to display the `ScheduledMessagesFragment` directly from the `MessageListFragment` leads to issues with the lazy initialization of the `attachHolder`. If you have any ideas of how to get this to work I would appreciate them greatly.

**Comment by klinker24** [comment]
I do have some concerns around this:

1. On the scheduled message screen, tapping the FAB to bring up the compose screen... There is really nothing distinguishing that compose "+" button from the normal one on the conversation list. When you hit that and it shows the exact same UI as the normal compose screen, without any indication that this is actually a scheduled message that you are going to create, I just feel as though that is going to be confusing to the user. They will hit that FAB and immediately think "why am I here, I was trying to create a scheduled message. How do I create a scheduled message if that button takes me to the same place as the compose button on the conversation list?"
2. With the 4th screenshot, I don't know if I like this UX. While you do have a message distinguishing that you are creating a scheduled message.. You are again shoving the user into the exact same UI for sending a regular message. They aren't going to understand that hitting the send button is going to save a regular message, when every other time they do it, it is sending a message immediately

I guess I am not quite sure why this change is something you are looking for. Pulse already allows you to schedule a message from the message list screen. If you long click the send button, it gives you options for what you have entered, including the ability to schedule the message instead of sending it. There is also an option to "schedule a message" in the three-dot overflow menu. Right now, these options redirect you to the scheduled messages screen and take you through the normal process. Would it be better to simply improve this flow, rather than trying to make an entirely new flow?

To me, it just seems like this is going to ultimately confuse the user by forcing them into the exact same UI that they are used to using for a different action (sending a message rather than scheduling one).

There is a lot of functionality on the main compose screen (recents, groups, all contacts) and I like the idea of exposing that functionality to the user when they are scheduling messages, but I am not sure that this is the way to go about doing that. If they wanted to be in a conversation to schedule the message, then they could just open the conversation already and do this. I am not sure I like switching away from the `ScheduledMessagesFragment` every time they schedule a new one. That removes the ability to schedule messages in bulk without constantly having to switch screens/contexts.

**Comment by sstream17** [comment]
I am a longtime Textra SMS user. This flow was modeled after how scheduling messages works in that app, especially screenshots 3 and 4. When scheduling a message in Textra, I was never confused whether I was sending a message now or scheduling it due to the icon and message notifying me so.

I understand how users from your app may get confused when hitting the FAB on the `ScheduledMessagesFragment` if this change would be implemented, because they are used to the current flow. If you do not wish to include this change into the app, I understand, but I would still appreciate a bit of help displaying the scheduled messages in the `attachHolder` as seen in screenshot 5.

**Comment by klinker24** [comment]
I am not quite sure what you are asking about or what you mean, sorry. The code for displaying the fragment is here:

https://github.com/klinker-apps/pulse-sms-android/blob/master/app/src/main/java/xyz/klinker/messenger/fragment/message/attach/AttachmentInitializer.kt#L108

While the code for when that button is displayed can be found here

https://github.com/klinker-apps/pulse-sms-android/blob/master/app/src/main/java/xyz/klinker/messenger/fragment/message/attach/AttachmentInitializer.kt#L129

Without more info on where you are stuck or more context or code examples of what you have tried, I don't really know if I can provide any more information. You should just be able to simulate clicking the scheduled messages button, to open that UI. You could do that anywhere in the code and it would work fine.

**Comment by sstream17** [comment]
Okay, I will look into that. I was thinking I would have to call the private method `viewScheduledMessages()` somehow but that's where I was running into issues with the `attachHolder` not been initialized yet.

It was around here where I wanted to get an instance of the `attachHolder` and display the messages:
https://github.com/sstream17/pulse-sms-android/blob/bd9bdb6a42d33bb1425e622d4fd014539fe9050c/app/src/main/java/xyz/klinker/messenger/fragment/message/send/SendMessageManager.kt#L378

So when the user hits send, how do I display the scheduled message button from within the `SendMessageManager`? I think it would be best to do so without copying the code from your second link. I'm trying not to violate the architecture but am having a hard time seeing how the pieces interact.

**Comment by klinker24** [comment]
You can just run the `AttachmentInitializer`'s initialize method again. That method queries the scheduled messages and displays the button, when applicable. You don't have to copy any code, just call the method.

**Comment by sstream17** [comment]
Ah okay, thank you!

Do you mind if we leave this issue open in case I run into any other questions in the future? Once I feel like I've implemented what I want I can go ahead and close it.

**Comment by klinker24** [comment]
You can always comment on a closed issue. I get notifications and reply the same way.

**Comment by sstream17** [comment]
Alright, then I will let you decide if you want to close this issue if it is not something you would like in the full app.

**Comment by klinker24** [comment]
I do not think that this rendition is something that I will want in the full app. Improving support for  scheduled messages will probably come down the road, but I do not know if this is the best way to accomplish that, in accordance with my above concerns.
