### ISSUE TITLE
Apple iMessage 'liked', 'loved' etc. message receive handling

### ISSUE THREAD

**Issue by Morganizer** [klinker-apps/pulse-sms-issues#978]
## Confirm this Issue

- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.
- [x] This is not a general support question. Support should be done over [email](mailto:luke@klinkerapps.com).

## Describe Your Request

when iPhone users respond to a text by liking, loving etcetera, android users receive the whole message back prefixed by  ‘Liked’ or whatever keyword.  If it is a group conversation and multiple people respond like this it really noisys up the conversation.

### Describe alternatives you've considered

Build in a parser to recognize the iMessage messages and handle them (ideally to mimick iMessage rendering, but at least to reduce the noise).  COULD even eventually enable pulse feature to replicate the iMessage feature in Pulse: I think the compatibility would be a huge selling point for Pulse.

### Additional information

(pseudo code):
 
```messages = array of messages objects in the conversation 
new = the new message

For x in messages.string:  (loop through messages in the conversation)
                If x in new.string:   (if it looks like an apple like message or something)

                               #parse the prefix
     
                               # append the new.sentBy and new.prefix to corresponding message.decorator

                                # exit without appending another message to the messages array
                Else:
                                Append new to messages


#Modify display(messages) to add graphic decorations to each message. ```

**Comment by klinker24** [comment]
Sorry, at this time, that isn't something that I have planned. 

On the reception side, sure, I could show a heart or a count next to a message for those that are "liked", but it isn't something that you could send back to iMessage. So it would be a confusing display feature with no feedback for the user and no ability for the Pulse user to "like" the message in return.

Pulse cannot simply send back a text that says `xxx liked "this message text"` as iMessage does. If you did that, iMessage would simply display it as a normal message in the conversation. It isn't as though it would be handled in the same way as users using iMessage. SMS does not contain the metadata that is used by iMessage to generate these "likes" or reactions. This feature is unique to iMessage and an Android device does not have the ability to play it back to iMessage. Because of this fact, this isn't something that I can include in Pulse. Unless there is a standard that is created to go both ways, this isn't something I will be able to add.

Pulse already allows you to blacklist by phrase, making it very easy to silence the noise generated by these messages. This isn't something that I am going to blacklist by default though. Some people do want to see these messages.

**Comment by Morganizer** [comment]
Cool thanks for your response, that makes sense...  [I hate proprietary whether it's Apple or anyone else!!!]

I hadn't learned about the blacklist by phrase feature, I must go explore that

With what you said in mind, you could make a preset blacklist 'mute iMessage likes' that could be a checkbox to turn on.
