### ISSUE TITLE
A way to disable swipe-right for settings panel

### ISSUE THREAD

**Issue by d4vex** [klinker-apps/pulse-sms-issues#979]
As i'm Oneplus user and this is my back gesture. When I swipe right from the edge of the screen it should get me one step back, instead i'm getting settings panel, which is also available when taping on icon in left top corner. So it would be great to have the option to disable this feature. Anyway great app! Thanks.

**Comment by klinker24** [comment]
Disabling the swipe for the navigation drawer is not at all normal, even if the button is there. This seems like an issue on OnePlus's side rather than my app's side. Any app would act the same way and I doubt that any other app would consider disabling this gesture... I guess I am not clear why it makes sense for my app to disable it, when this seems like it is a system wide issue.

Swiping to open the navigation drawer isn't a feature, it is simply the way that the navigation drawer works

**Comment by d4vex** [comment]
Don't know if this normal behavior, but even on Samsung phone with Android 10, when is set "back gesture" in navigation bar settings, it works fine in every other app. So this Oneplus or better android 10 back gesture actually works similar and in every app but Pulse. Nine email, whatsapp, telegram everyone i tried.

**Comment by klinker24** [comment]
The app works as expected on my S10 with gestures, so I don't know what you mean.

I do not see myself adding a preference like this within Pulse's main settings menu, sorry. With this app, I want to stay away from little "tweak" preferences. The app is open source though, and there is a specific open source section of settings where you could implement and maintain this preference. I discuss this in the app's readme

https://github.com/klinker-apps/pulse-sms-android

**Comment by d4vex** [comment]
Ok, understood. Thanks
